# config/meta.yml

meta_product_name: "sprout"
meta_title: "sprout - Find your perfect plant."
meta_description: "sprout is a web application created to find the perfect plant for your home."
meta_image: "og-img-tag-sprout.png"                       # should exist in `app/assets/images/`
